Repository Laurarestrepo03/Ocarina-Galaxian, pull requests merged in 2024-05, with the labels that each got.

#27 Se finaliza funcionalidad que muestra el fondo de estrellas con movimiento
  assets/cfg/starfield.json
  src/create/prefab_creator.py
  src/ecs/components/c_star_field.py
  src/ecs/systems/s_star_field.py
  src/engine/game_engine.py
Labels: enhancement

#32 [Feature] Colisión balas enemigas y balas jugador
  assets/cfg/enemies.json
  assets/cfg/enemy_explosion.json
  assets/cfg/player_bullet.json
  assets/cfg/player_explosion.json
  src/create/prefab_creator.py
  src/ecs/components/c_animation.py
  src/ecs/components/c_explosion_state.py
  src/ecs/systems/s_animation.py
  src/ecs/systems/s_collision_bullet_enemy.py
  src/ecs/systems/s_collision_bullet_player.py
  src/ecs/systems/s_explosion_state.py
  src/engine/game_engine.py
  src/engine/service_locator.py
  src/engine/services/sounds_service.py
Labels: enhancement

#34 [Feature] Implementación para pausar el juego
  assets/cfg/interface.json
  src/create/prefab_creator.py
  src/ecs/components/c_surface.py
  src/ecs/components/tags/c_tag_pause.py
  src/ecs/systems/s_pause.py
  src/ecs/systems/s_rendering.py
  src/engine/game_engine.py
  src/engine/service_locator.py
  src/engine/services/fonts_services.py
Labels: enhancement

#38 [Doc] Avance semana 5
  docs/avance-semana-5.pdf
Labels: documentation

#40 [Fix] Sistema unificado para bala del jugador
  .github/ISSUE_TEMPLATE/tarea.md
  assets/cfg/player_bullet.json
  src/create/prefab_creator.py
  src/ecs/components/c_player_bullet_state.py
  src/ecs/components/tags/c_tag_bullet.py
  src/ecs/components/tags/c_tag_enemy_bullet.py
  src/ecs/components/tags/c_tag_player_bullet.py
  src/ecs/systems/s_bullet_limit.py
  src/ecs/systems/s_collision_bullet_enemy.py
  src/ecs/systems/s_collision_bullet_player.py
  src/ecs/systems/s_enemy_bullet_spawn.py
  src/ecs/systems/s_player_bullet_rest_pos.py
  src/ecs/systems/s_player_bullet_spawn.py
  src/ecs/systems/s_player_bullet_state.py
  src/engine/game_engine.py
Labels: fix

#45 Eliminacion liena cambio posicion enemigos
  src/ecs/systems/s_enemy_movement.py
Labels: fix

#49 [Fix] Velocidad de las estrellas en pausa, velocidad de jugador y otros ajustes
  assets/cfg/enemies.json
  assets/cfg/player.json
  src/create/prefab_creator.py
  src/ecs/systems/s_player_bullet_state.py
  src/ecs/systems/s_star_field.py
  src/engine/game_engine.py
Labels: fix

#52 [Doc] Avance semana 6
  docs/avance-semana-6.pdf
  src/create/prefab_creator.py
  src/engine/game_engine.py
Labels: documentation

#53 [Fix] Delay en disparo de balas enemigas
  assets/cfg/level_01.json
  src/create/prefab_creator.py
  src/ecs/components/c_enemy_bullet_spawner.py
  src/ecs/systems/s_enemy_bullet_spawn.py
  src/engine/game_engine.py
Labels: fix

#55 Feature/8 10 11 sistem game manager
  assets/cfg/interface.json
  src/create/prefab_creator.py
  src/ecs/components/c_game_state.py
  src/ecs/components/c_surface.py
  src/ecs/components/tags/c_tag_level.py
  src/ecs/components/tags/c_tag_life.py
  src/ecs/components/tags/c_tag_ready.py
  src/ecs/systems/s_collision_bullet_player.py
  src/ecs/systems/s_enemy_bullet_spawn.py
  src/ecs/systems/s_game_manager.py
  src/ecs/systems/s_movement.py
  src/ecs/systems/s_player_bullet_state.py
  src/ecs/systems/s_rendering.py
  src/engine/game_engine.py
Labels: enhancement

#57 Fix/9 textos score 1up
  assets/cfg/interface.json
  src/create/prefab_creator.py
  src/ecs/components/c_level.py
  src/ecs/components/tags/c_tag_high_score.py
  src/ecs/components/tags/c_tag_score.py
  src/ecs/systems/s_game_manager.py
  src/ecs/systems/s_player_bullet_state.py
  src/ecs/systems/s_update_high_score.py
  src/ecs/systems/s_update_score.py
  src/engine/game_engine.py
Labels: fix

#58 Se ajusta parpadeo en s_rendering y s_blink
  src/ecs/systems/s_blink.py
  src/ecs/systems/s_rendering.py
Labels: fix

#60 Fix/balas enemigas ready
  assets/cfg/interface.json
  src/ecs/systems/s_collision_bullet_player.py
  src/ecs/systems/s_game_manager.py
Labels: enhancement, fix

#61 [Fix] Servicio para archivos de configuracion y otros ajustes
  assets/cfg/enemies.json
  assets/cfg/interface.json
  assets/cfg/level_01.json
  src/ecs/systems/s_collision_bullet_player.py
  src/ecs/systems/s_enemy_bullet_spawn.py
  src/engine/game_engine.py
  src/engine/service_locator.py
  src/engine/services/configs_service.py
  src/engine/services/fonts_service.py
Labels: fix

#62 Cambios para resolver los problemas de la aparición de balas en ready y el pause al morir.
  src/ecs/components/c_game_state.py
  src/ecs/systems/s_collision_bullet_player.py
  src/ecs/systems/s_game_manager.py
  src/engine/game_engine.py
Labels: fix

#63 [Feature] Ataque dinámico de enemigos
  assets/cfg/level_01.json
  src/create/prefab_creator.py
  src/ecs/components/c_enemy_attack.py
  src/ecs/components/c_enemy_bullet_spawner_hunting.py
  src/ecs/components/c_enemy_steering.py
  src/ecs/components/c_level.py
  src/ecs/components/tags/c_tag_enemy.py
  src/ecs/systems/s_collision_enemy_player.py
  src/ecs/systems/s_enemy_attack.py
  src/ecs/systems/s_enemy_attack_fire.py
  src/ecs/systems/s_enemy_bullet_spawn_convoy.py
  src/ecs/systems/s_enemy_movement.py
  src/ecs/systems/s_enemy_steering.py
  src/ecs/systems/s_player_limit.py
  src/engine/game_engine.py
  src/engine/services/sounds_service.py
Labels: enhancement

#64 Ajuste bug cuando el jugador se ubica en los extremos de la pantalla
  src/ecs/systems/s_enemy_movement.py
Labels: fix
